name: Build Hyprland Artifacts

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Get all submodules
        run: |
          git submodule update --init --recursive -- ./build_files/hyprland_source

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            podman login ghcr.io \
            --username "${{ github.actor }}" \
            --password-stdin

      - name: Pull Hyprland Base Packages
        run: |
          podman pull \
            ghcr.io/${{ github.repository_owner }}/hyprland-base-packages:latest

      - name: Build Hyprland
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/hyprland-artifacts"
          podman build \
            --progress=plain \
            --file Hyprland.Containerfile \
            --tag "${IMAGE}:latest" \
            .

      - name: Push Hyprland Artifacts
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/hyprland-artifacts"
          podman push "${IMAGE}:latest"
