name: Build UWSM Artifacts

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Needed so `just` can find the Justfile
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 #v4.0.0

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            podman login ghcr.io \
            --username "${{ github.actor }}" \
            --password-stdin

      - name: Get Fedora Version
        run: |
          FEDORA_VERSION=$(just fedora_version)
          echo "FEDORA_VERSION=${FEDORA_VERSION}" >> $GITHUB_ENV

      - name: Get UWSM Version
        run: |
          UWSM_VERSION=$(just uwsm_version)
          echo "UWSM_VERSION=${UWSM_VERSION}" >> $GITHUB_ENV

      - name: Build UWSM
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/uwsm-artifacts"
          podman build \
            --progress=plain \
            --file UWSM.Containerfile \
            --tag "${IMAGE}:latest" \
            --build-arg FEDORA_VERSION=${FEDORA_VERSION} \
            --build-arg UWSM_VERSION=${UWSM_VERSION} \
            .

      - name: Push UWSM Artifacts
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/uwsm-artifacts"
          podman push "${IMAGE}:latest"
