name: Build Hyprland Ecosystem

on:
  push:
    paths:
      - 'Hyprland_Ecosystem.Containerfile'
      - 'Hyprland.Containerfile'
      - 'build_files/hyprland_ecosystem_source'
  pull_request:
    paths:
      - 'Hyprland_Ecosystem.Containerfile'
      - 'Hyprland.Containerfile'
      - 'build_files/hyprland_ecosystem_source'
  workflow_run:
    workflows:
      - "Build Hyprland Artifacts"
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    if: >
      github.event_name == 'push' ||
      github.event_name == 'pull_request' ||
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'workflow_run' &&
        github.event.workflow_run.conclusion == 'success'
      )
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        run: |
          git submodule -C ./build_files/hyprland_ecosystem_source \
          submodule update --init --recursive

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Pull Hyprland Base Packages
        run: |
          podman pull \
            ghcr.io/${{ github.repository_owner }}/hyprland-base-packages:latest

      - name: Pull Hyprland Artifacts
        run: |
          podman pull \
            ghcr.io/${{ github.repository_owner }}/hyprland-artifacts:latest

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            podman login ghcr.io \
            --username "${{ github.actor }}" \
            --password-stdin

      - name: Build Hyprland Ecosystem
        run: |
          podman build \
            --progress=plain \
            --file Hyprland_Ecosystem.Containerfile \
            --tag ghcr.io/${{ github.repository_owner }}/hyprland-ecosystems:latest \
            .

      - name: Push Hyprland Base Packages
        run: |
          podman push \
            ghcr.io/${{ github.repository_owner }}/hyprland-base-packages:latest
