name: Build Hyprland Cache

on:
  push:
    paths:
      - 'build_files/hyprland_source/**'
      - '.gitmodules'
      - 'Hyprland.Containerfile'
  workflow_dispatch:

env:
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  CACHE_IMAGE_NAME: hyprland-artifacts

jobs:
  build_hyprland:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Lowercase Registry for Podman
        run: echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> ${GITHUB_ENV}

      - name: Build Image with Podman
        run: |
          podman build \
          -t ${{ env.IMAGE_REGISTRY }}/${{ env.CACHE_IMAGE_NAME }}:latest \
          -f ./Hyprland.Containerfile .

      - name: Log in to GitHub Container Registry
        run: |
          podman login ghcr.io -u ${{ github.actor }} --password-stdin <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Push to GitHub Container Registry
        run: |
          podman push ${{ env.IMAGE_REGISTRY }}/${{ env.CACHE_IMAGE_NAME }}:latest
